package parity

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.southernstorm.noise.protocol.HandshakeState
import com.southernstorm.noise.protocol.Noise
import java.io.File
import java.nio.ByteBuffer
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals

/**
 * V1 parity tests: load JSON vectors generated by Rust (l3 vector-gen)
 * and reproduce them using JVM HMAC + Signal's noise-java fork.
 *
 * If every assertion passes, both platforms speak the same V1 protocol.
 */
class CryptoParityTest {

    private val mapper = ObjectMapper()
    private val vectorsDir = locateVectorsDir()

    private fun locateVectorsDir(): File {
        // tests/parity-test/<gradle-cwd> → vectors are at
        // <repoRoot>/shared/vectors/v1
        var dir = File(System.getProperty("user.dir"))
        repeat(5) {
            val candidate = File(dir, "shared/vectors/v1")
            if (candidate.isDirectory) return candidate
            dir = dir.parentFile ?: return@repeat
        }
        error("could not locate shared/vectors/v1 from ${System.getProperty("user.dir")}")
    }

    private fun loadVector(name: String): JsonNode =
        mapper.readTree(File(vectorsDir, name))

    private fun hexDecode(hex: String): ByteArray {
        require(hex.length % 2 == 0)
        return ByteArray(hex.length / 2) {
            ((Character.digit(hex[it * 2], 16) shl 4) or Character.digit(hex[it * 2 + 1], 16)).toByte()
        }
    }

    private fun hmacSha256(key: ByteArray, data: ByteArray): ByteArray {
        val mac = Mac.getInstance("HmacSHA256")
        mac.init(SecretKeySpec(key, "HmacSHA256"))
        return mac.doFinal(data)
    }

    // -------- HMAC-keyed derivations --------

    @Test
    fun `SAS derivation matches Rust vectors`() {
        val v = loadVector("sas.json")
        val label = v["label"].asText().toByteArray(Charsets.UTF_8)
        v["cases"].forEach { case ->
            val h = hexDecode(case["h_hex"].asText())
            val mac = hmacSha256(label, h)
            val sasInt = ByteBuffer.wrap(mac, 0, 4).int.toLong() and 0xFFFFFFFFL
            val sasValue = (sasInt % 1_000_000L).toInt()
            val sasString = "%06d".format(sasValue)

            assertEquals(
                case["sas_value"].asInt(),
                sasValue,
                "SAS int mismatch for h=${case["h_hex"].asText()}",
            )
            assertEquals(
                case["sas_string"].asText(),
                sasString,
                "SAS string mismatch",
            )
        }
    }

    @Test
    fun `PRS derivation matches Rust vectors`() {
        val v = loadVector("prs.json")
        val label = v["label"].asText().toByteArray(Charsets.UTF_8)
        v["cases"].forEach { case ->
            val ck = hexDecode(case["ck_hex"].asText())
            val prs = hmacSha256(label, ck)
            assertContentEquals(
                hexDecode(case["prs_hex"].asText()),
                prs,
                "PRS mismatch for ck=${case["ck_hex"].asText()}",
            )
        }
    }

    @Test
    fun `SES derivation matches Rust vectors`() {
        val v = loadVector("ses.json")
        val label = v["label"].asText().toByteArray(Charsets.UTF_8)
        v["cases"].forEach { case ->
            val h = hexDecode(case["h_hex"].asText())
            val ses = hmacSha256(label, h)
            assertContentEquals(
                hexDecode(case["ses_hex"].asText()),
                ses,
                "SES mismatch for h=${case["h_hex"].asText()}",
            )
        }
    }

    @Test
    fun `Presence token derivation matches Rust vectors`() {
        val v = loadVector("presence.json")
        val label = v["label"].asText().toByteArray(Charsets.UTF_8)
        v["cases"].forEach { case ->
            val prs = hexDecode(case["prs_hex"].asText())
            val bucket = case["bucket"].asLong()
            val data = ByteBuffer.allocate(label.size + 8)
                .put(label)
                .putLong(bucket)
                .array()
            val token32 = hmacSha256(prs, data)
            val token = token32.copyOfRange(0, 8)
            assertContentEquals(
                hexDecode(case["token_hex"].asText()),
                token,
                "Presence token mismatch for bucket=$bucket",
            )
        }
    }

    // -------- Noise wire vectors --------

    private fun runNoise(
        pattern: String,
        prologue: ByteArray,
        initiatorStaticPriv: ByteArray,
        responderStaticPriv: ByteArray,
        initiatorEphemeralPriv: ByteArray,
        responderEphemeralPriv: ByteArray,
        responderStaticPub: ByteArray? = null,
    ): Triple<List<ByteArray>, ByteArray, ByteArray> {
        val initiator = HandshakeState(pattern, HandshakeState.INITIATOR).apply {
            setPrologue(prologue, 0, prologue.size)
            localKeyPair.setPrivateKey(initiatorStaticPriv, 0)
            fixedEphemeralKey.setPrivateKey(initiatorEphemeralPriv, 0)
            responderStaticPub?.let { remotePublicKey.setPublicKey(it, 0) }
            start()
        }
        val responder = HandshakeState(pattern, HandshakeState.RESPONDER).apply {
            setPrologue(prologue, 0, prologue.size)
            localKeyPair.setPrivateKey(responderStaticPriv, 0)
            fixedEphemeralKey.setPrivateKey(responderEphemeralPriv, 0)
            start()
        }

        fun writeMsg(state: HandshakeState): ByteArray {
            val buf = ByteArray(Noise.MAX_PACKET_LEN)
            val len = state.writeMessage(buf, 0, null, 0, 0)
            return buf.copyOf(len)
        }
        fun readMsg(state: HandshakeState, msg: ByteArray) {
            val payload = ByteArray(Noise.MAX_PACKET_LEN)
            state.readMessage(msg, 0, msg.size, payload, 0)
        }

        val messages = mutableListOf<ByteArray>()

        // msg1
        messages += writeMsg(initiator); readMsg(responder, messages.last())
        // msg2
        messages += writeMsg(responder); readMsg(initiator, messages.last())

        // XX has 3 messages; IK has 2.
        if (initiator.action == HandshakeState.WRITE_MESSAGE) {
            messages += writeMsg(initiator); readMsg(responder, messages.last())
        }

        return Triple(
            messages.toList(),
            initiator.handshakeHash.copyOf(),
            responder.handshakeHash.copyOf(),
        )
    }

    @Test
    fun `Noise XX wire bytes match Rust vectors`() {
        val v = loadVector("noise-xx.json")
        val pattern = v["noise_pattern"].asText()
        val prologue = hexDecode(v["prologue_hex"].asText())
        val inputs = v["inputs"]
        val (msgs, initHash, respHash) = runNoise(
            pattern = pattern,
            prologue = prologue,
            initiatorStaticPriv = hexDecode(inputs["initiator_static_priv_hex"].asText()),
            responderStaticPriv = hexDecode(inputs["responder_static_priv_hex"].asText()),
            initiatorEphemeralPriv = hexDecode(inputs["initiator_ephemeral_priv_hex"].asText()),
            responderEphemeralPriv = hexDecode(inputs["responder_ephemeral_priv_hex"].asText()),
        )
        val outputs = v["outputs"]
        assertContentEquals(hexDecode(outputs["msg1_hex"].asText()), msgs[0], "XX msg1")
        assertContentEquals(hexDecode(outputs["msg2_hex"].asText()), msgs[1], "XX msg2")
        assertContentEquals(hexDecode(outputs["msg3_hex"].asText()), msgs[2], "XX msg3")
        assertContentEquals(
            hexDecode(outputs["transcript_hash_hex"].asText()),
            initHash,
            "XX transcript hash (initiator)",
        )
        assertContentEquals(initHash, respHash, "XX transcript symmetry")
    }

    @Test
    fun `Noise IK wire bytes match Rust vectors`() {
        val v = loadVector("noise-ik.json")
        val pattern = v["noise_pattern"].asText()
        val prologue = hexDecode(v["prologue_hex"].asText())
        val inputs = v["inputs"]
        val (msgs, initHash, respHash) = runNoise(
            pattern = pattern,
            prologue = prologue,
            initiatorStaticPriv = hexDecode(inputs["initiator_static_priv_hex"].asText()),
            responderStaticPriv = hexDecode(inputs["responder_static_priv_hex"].asText()),
            initiatorEphemeralPriv = hexDecode(inputs["initiator_ephemeral_priv_hex"].asText()),
            responderEphemeralPriv = hexDecode(inputs["responder_ephemeral_priv_hex"].asText()),
            responderStaticPub = hexDecode(inputs["responder_static_pub_hex"].asText()),
        )
        val outputs = v["outputs"]
        assertContentEquals(hexDecode(outputs["msg1_hex"].asText()), msgs[0], "IK msg1")
        assertContentEquals(hexDecode(outputs["msg2_hex"].asText()), msgs[1], "IK msg2")
        assertContentEquals(
            hexDecode(outputs["transcript_hash_hex"].asText()),
            initHash,
            "IK transcript hash",
        )
        assertContentEquals(initHash, respHash, "IK transcript symmetry")
    }
}
